// Copyright 2025 Medvedev Dan (https://github.com/Firegreat78)

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef CLIENTCONNECTION_H
#define CLIENTCONNECTION_H

#include <cstdint>
#include <string>
#include <thread>
#include <array>
#include <vector>
#include "json.hpp"

#include <WinSock2.h>

using json = nlohmann::json;

constexpr size_t CLIENT_BUFFER_SIZE = 4000;

class ClientConnection
{
    SOCKET socket;
    std::thread thread;
    size_t thread_id;
    bool pendingDelete;
    
    std::array<char, CLIENT_BUFFER_SIZE> recv_buf;
    int bytes_received;
    std::string incomplete_json;
    std::vector<json> jsons_from_client;
    std::vector<json> jsons_to_client;
    
    static void handle_client(ClientConnection* const);
    void setRecvTimeout(int);
    void setSendTimeout(int);
    void onBytesReceived(); // recv > 0
    bool sendAll(std::string const&);

    ClientConnection(const ClientConnection&) = delete;
    ClientConnection& operator=(const ClientConnection&) = delete;
    std::string getClientInfo();
    
    public:
    ClientConnection& operator=(ClientConnection&&);
    ClientConnection(SOCKET&, size_t const);
    bool isPendingToDelete() const;
    void joinThread();
    
    ~ClientConnection();
};

#endif // CLIENTCONNECTION_H