// Copyright 2025 Medvedev Dan (https://github.com/Firegreat78)

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Logger.h"

#include <filesystem>
#include <iomanip>
#include <iostream>
#include <cstdlib>
#include <sstream>

Logger::Logger()
{
    try
    {
        std::filesystem::path BASE_FOLDER(".\\logs");
        std::string fileName = generateLogFilename();
        std::filesystem::path logPath = BASE_FOLDER / fileName;
        logFile_.open(logPath, std::ios::app);
    }
    catch (std::exception const &e)
    {
        std::cerr << "Failed to create an Logger object. The server wiil shut down immediately." << std::endl;
        std::exit(EXIT_FAILURE);
    }
}

std::string Logger::getCurrentTimestamp() const
{
    auto now = std::chrono::system_clock::now();
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()) % 1000; // Get milliseconds

    std::time_t t = std::chrono::system_clock::to_time_t(now);
    std::tm tm = *std::localtime(&t);

    std::ostringstream oss;
    oss << std::put_time(&tm, "[%Y-%m-%d %H:%M:%S") << '.' << std::setfill('0') << std::setw(3) << ms.count();
    return oss.str() + ']';
}

std::string Logger::generateLogFilename() const
{
    auto now = std::chrono::system_clock::now();
    std::time_t t = std::chrono::system_clock::to_time_t(now);
    std::tm tm = *std::localtime(&t);

    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y_%m_%d_%H%M%S") << ".log";
    return oss.str();
}

Logger& Logger::getInstance()
{
    static Logger instance;
    return instance;
}


void Logger::log(std::string const& msg)
{
    log(msg.data(), msg.length());
}

void Logger::log(char const* const ptr, size_t const length)
{
    constexpr bool do_cout = true;
    std::lock_guard<std::mutex> lock(mutex_); // no two threads try to log to the logfile simultaneously
    std::string const timestamp = getCurrentTimestamp();
    logFile_ << timestamp << " - " << "[";
    if (do_cout) std::cout << timestamp << " - " << "[";
    for (size_t i = 0; i < length; i++)
    {
        logFile_ << ptr[i];
        if (do_cout) std::cout << ptr[i];
    }
    logFile_ << "]" << std::endl;
    if (do_cout) std::cout << "]" << '\n';
}

Logger::~Logger()
{
    if (logFile_.is_open())
    {
        logFile_.flush();
        logFile_.close();
    }
}
